In [2]:
import numpy as np
import pandas as pd

In [4]:
import math
def shifter(digit, direction):
    digit=digit.values
    dimension=math.floor(math.sqrt(digit.shape[0]))
    digit=digit.reshape((math.floor(math.sqrt(digit.shape[0])), -1))
    if direction=='left':
        newcol=np.zeros((dimension, 1), np.int64)
        newdig=np.delete(digit, 0, axis=1)
        newdig=np.hstack((newdig, newcol))
    elif direction=='right':
        newcol=np.zeros((dimension, 1), dtype=np.int64)
        newdig=np.delete(digit, dimension-1, axis=1)
        newdig=np.hstack((newcol, newdig))
    elif direction=='up':
        newrow=np.zeros((1, dimension), dtype=np.int64)
        newdig=np.delete(digit, 0, axis=0)
        newdig=np.vstack((newdig, newrow))
    else:
        newrow=np.zeros((1, dimension), dtype=np.int64)
        newdig=np.delete(digit, dimension-1, axis=0)
        newdig=np.vstack((newrow, newdig))
    return newdig.reshape((-1, 1)).squeeze()


In [3]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1)

In [10]:
X, y= mnist['data'], mnist['target'].astype(int)
print(X)
in_training=15000
X_train, y_train, X_test, y_test = X[:in_training, :], y[:in_training], X[in_training:, :], y[in_training:]
shuffled_indices=np.random.permutation(in_training)
X_train, y_train = X_train[shuffled_indices, :], y_train[shuffled_indices]

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
X_left=X_train.apply(lambda row : shifter(row, 'left'), axis=1)
X_right=X_train.apply(lambda row : shifter(row, 'right'), axis=1)
X_up=X_train.apply(lambda row : shifter(row, 'up'), axis=1)
X_down=X_train.apply(lambda row : shifter(row, 'down'), axis=1)


AttributeError: 'numpy.ndarray' object has no attribute 'apply'

In [7]:
X_left

17509    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
8173     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
13217    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2986     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2551     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
                               ...                        
8524     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
7103     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2928     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
13276    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
24188    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Length: 25000, dtype: object

In [7]:
import gc

X_new=pd.concat([X_train, X_left], ignore_index=True)
del X_left
gc.collect()

X_new=pd.concat([X_new, X_right], ignore_index=True)
del X_right
gc.collect()

X_new=pd.concat([X_new, X_up], ignore_index=True)
del X_up
gc.collect()

X_new=pd.concat([X_new, X_down], ignore_index=True)
del X_down
gc.collect()

0

In [8]:
X_new

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
74995     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
74996     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
74997     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
74998     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
74999     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

       pixel10  ...  pixel776  pixel777  pixel778  pixel779  pixel780  \
0          0.0  ...       0.0       0.0       0.0       0.0       0.0   
1          0.0  ...       0.0       0.0       0.0       0.0       0.0   
2          0.0  ...       0.0       0.0       0.0       0.0       0.0   
3          0.0  ...       0.0       0.0       0.0       0.0       0.0   
4          0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
74995      NaN  ...       NaN       NaN       NaN       NaN       NaN   
74996      NaN  ...       NaN       NaN       NaN       NaN       NaN   
74997      NaN  ...       NaN       NaN       NaN       NaN       NaN   
74998      NaN  ...       NaN       NaN       NaN       NaN       NaN   
74999      NaN  ...       NaN       NaN       NaN       NaN       NaN   

       pixel781  pixel782  pixel783  pixel784  \
0           0.0       0.0       0.0       0.0   
1           0.0       0.0       0.0       0.0   
2           0.0       0.0       0.0       0.0   
3           0.0       0.0       0.0       0.0   
4           0.0       0.0       0.0       0.0   
...         ...       ...       ...       ...   
74995       NaN       NaN       NaN       NaN   
74996       NaN       NaN       NaN       NaN   
74997       NaN       NaN       NaN       NaN   
74998       NaN       NaN       NaN       NaN   
74999       NaN       NaN       NaN       NaN   

                                                       0  
0                                                    NaN  
1                                                    NaN  
2                                                    NaN  
3                                                    NaN  
4                                                    NaN  
...                                                  ...  
74995  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
74996  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
74997  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
74998  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
74999  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  

[75000 rows x 785 columns]

In [9]:

from skimage import measure, morphology


def count_cycles_in_digit(image):
    """Count the number of topological cycles (closed loops) in a digit image"""
    # Convert to numpy array if it's a pandas Series/DataFrame
    if hasattr(image, 'values'):
        image = image.values
    
    # Ensure image is properly shaped as numpy array
    image = np.array(image)
    
    # Reshape to 28x28
    try:
        if image.size == 784:  # Flattened MNIST image
            image = image.reshape(28, 28)
        elif image.shape == (28, 28):
            pass  # Already correct shape
        else:
            # Try to reshape to 28x28
            image = image.reshape(28, 28)
    except:
        return 0
    
    # Convert to binary (MNIST has white digits on black background)
    binary = image > 128
    
    try:
        # Remove noise and small artifacts
        cleaned = morphology.remove_small_objects(binary, min_size=10)
        cleaned = morphology.remove_small_holes(cleaned, area_threshold=10)
        
        # Find contours
        contours = measure.find_contours(cleaned, 0.5)
        
        cycle_count = 0
        for contour in contours:
            if len(contour) > 3:  # Need at least 4 points for a closed contour
                # Check if contour is closed (start and end points are close)
                start = contour[0]
                end = contour[-1]
                distance = np.sqrt((start[0]-end[0])**2 + (start[1]-end[1])**2)
                if distance < 2.0:  # Threshold for closed contour
                    cycle_count += 1
        
        return cycle_count
    except Exception as e:
        # Fallback for any processing errors
        return 0

def add_cycle_count_to_dataset(X_data, batch_size=1000, verbose=True):
    """Add cycle count as an additional feature to the dataset in batches"""
    # Convert to numpy array if it's a pandas DataFrame
    if hasattr(X_data, 'values'):
        X_data = X_data.values
        print("Converted pandas DataFrame to numpy array")
    
    if verbose:
        print(f"Adding cycle count feature to dataset with shape: {X_data.shape}")
    
    # Pre-allocate array for cycle counts
    cycle_counts = np.zeros(X_data.shape[0], dtype=np.uint8)
    
    # Process in batches to manage memory
    total_batches = (X_data.shape[0] + batch_size - 1) // batch_size
    
    for batch_idx in range(0, X_data.shape[0], batch_size):
        batch_end = min(batch_idx + batch_size, X_data.shape[0])
        
        if verbose and batch_idx % (batch_size * 10) == 0:
            print(f"Processing batch {batch_idx//batch_size + 1}/{total_batches}")
        
        for i in range(batch_idx, batch_end):
            cycle_counts[i] = count_cycles_in_digit(X_data[i])
    
    # Add cycle count as the last feature column
    X_with_cycles = np.hstack([X_data, cycle_counts.reshape(-1, 1)])
    
    if verbose:
        print(f"Dataset shape with cycle counts: {X_with_cycles.shape}")
        
        # Print cycle count distribution
        unique_cycles, counts = np.unique(cycle_counts, return_counts=True)
        print("Cycle count distribution:")
        for cycles, count in zip(unique_cycles, counts):
            percentage = (count / len(cycle_counts)) * 100
            print(f"  {cycles} cycles: {count:6d} samples ({percentage:5.1f}%)")
    
    # Free memory
    del cycle_counts
    gc.collect()
    
    return X_with_cycles

# Test with a small sample first to make sure it works
def test_cycle_counting(X_data, num_test=5):
    """Test cycle counting on a few samples"""
    print("Testing cycle counting on a few samples...")
    
    # Convert to numpy array if it's pandas
    if hasattr(X_data, 'values'):
        X_data_np = X_data.values
    else:
        X_data_np = X_data
    
    for i in range(min(num_test, X_data_np.shape[0])):
        cycles = count_cycles_in_digit(X_data_np[i])
        print(f"Sample {i}: {cycles} cycles")
    
    # Test the batch function on a small subset
    X_test_subset = X_data_np[:100]
    X_with_cycles_test = add_cycle_count_to_dataset(X_test_subset, verbose=True)
    return X_with_cycles_test

# First, let's check what type X_new is
print(f"X_new type: {type(X_new)}")
print(f"X_new shape: {X_new.shape if hasattr(X_new, 'shape') else 'No shape attribute'}")
print(f"X_new columns: {X_new.columns if hasattr(X_new, 'columns') else 'No columns attribute'}")

# Now test on a small subset
print("\nTesting cycle counting on small subset...")
X_new_small_with_cycles = test_cycle_counting(X_new, num_test=5)

# If the test works, apply to the full dataset
#print("\n" + "="*50)
#print("Applying cycle counting to full dataset...")
#X_new_with_cycles = add_cycle_count_to_dataset(X_new, batch_size=1000, verbose=True)

#print("Cycle counting completed successfully!")

X_new type: <class 'pandas.core.frame.DataFrame'>
X_new shape: (75000, 785)
X_new columns: Index([  'pixel1',   'pixel2',   'pixel3',   'pixel4',   'pixel5',   'pixel6',
         'pixel7',   'pixel8',   'pixel9',  'pixel10',
       ...
       'pixel776', 'pixel777', 'pixel778', 'pixel779', 'pixel780', 'pixel781',
       'pixel782', 'pixel783', 'pixel784',          0],
      dtype='object', length=785)

Testing cycle counting on small subset...
Testing cycle counting on a few samples...


: 

Adding cycle count feature to dataset with shape: (125000, 785)
Processing batch 1/125


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()